### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by mackeper** [top-tier-ci-coders/ContinuousIntegrationServer#1]
We need to create a README which contains all info about the project and how to build it.
Note: We must also have a statement of the contributions.

From grading assessment:
The students document in the README how compilation has been implemented and unit-tested.
The students document in the README how test execution has been implemented and unit-tested.
Document in the README how notification has been implemented and unit-tested.

**Comment by mstniy** [comment]
I'll start writing a README. All constributors shall add their statement of contributions.

**Comment by mackeper** [comment]
The students document in the README how notification has been implemented and unit-tested.

**Comment by philippaornell** [comment]
We have a new issue regarding this. :)
