### ISSUE TITLE
Add documentation for classes

### ISSUE THREAD

**Issue by philippaornell** [top-tier-ci-coders/ContinuousIntegrationServer#44]
It is stated that in the assessment that all public classes and methods should be well documented. We have not yet documented and explained what the different classes do. For example what does the GitHandler do, this should be documented at the top of the class.

**Comment by philippaornell** [comment]
We can create several issues for each class that needs to be documented, this issue just works as a reminder for us to not forget about documentation. :)

**Comment by mackeper** [comment]
All classes documented
