### ISSUE TITLE
P+ property, the CI server keeps the history of the past builds

### ISSUE THREAD

**Issue by philippaornell** [top-tier-ci-coders/ContinuousIntegrationServer#45]
If we want P+, the CI server should keep the history of the past builds. This history persists even if the server is rebooted. Each build is given a unique URL, that is accessible to get the build information (commit identifier, build date, build logs). One URL exists to list all builds.

Although, we should focus on getting all P properties done first. I just created this issue in case we have time.

**Comment by mackeper** [comment]
I've set up a subdomain for this. (api.macke.pro) and might be able to create a minimum API to get build info. This will require our CI server to do a POST request to this other server.

**Comment by mackeper** [comment]
* One URL to list all build
* Unique URL to each build (build information (commit identifier, build date, build logs))
* We need to store information about the commiter.

Could be solved by letting request_push() also write the status to a file.
Then, let handle() handle two other types of GET requests, one to list all builds and one for a unique build. List all build should just return the name of the files in a chosen directory and the unique build should return the content of the file.

Maybe a new class with three functions: 
* string[] ListBuilds()
* string GetBuildStatus(string build_id)
* void SetBuildStatus(string build_id, string status)

**Comment by gpihl** [comment]
We have this now! Closing.
