### ISSUE TITLE
Make request_push return something

### ISSUE THREAD

**Issue by mstniy** [top-tier-ci-coders/ContinuousIntegrationServer#54]
At the moment it returns void, making it impossible to programmatically test. It needs to return where it failed/if it failed. So that it'll be testable. handlePushEvent can read the return value and set the HTTP response, making itself testable, too.

**Comment by agylling** [comment]
Fixed in #51

**Comment by mstniy** [comment]
It needs to return a more detailed response, not just a boolean. So that it'll be more testable.
I'll be working on this
