### ISSUE TITLE
 Create class skeleton for the CI class

### ISSUE THREAD

**Issue by mstniy** [top-tier-ci-coders/ContinuousIntegrationServer#7]

**Comment by mstniy** [comment]
It should include functions to pull branches from Github, building code, testing code and sending status emails.

**Comment by agylling** [comment]
We will start working on this now

**Comment by philippaornell** [comment]
Hm, I was going to start creating JUnit tests for the CI skeleton code we pushed yesterday, but I need this to be merged first, so I can easily create tests for it. Maybe we shall split this issue into two? I don't think it is super important that the skeleton has test code with it. Right now I can't create the tests (it is unnecessary work if the skeleton isnt approved). Have a look at what we pushed yesterday and see if you approve this or want changes. :)

**Comment by agylling** [comment]
Yeh, I'll create a seperate issue for testing
