### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by philippaornell** [top-tier-ci-coders/ContinuousIntegrationServer#71]
A lot is filled in but add statement of contributions and what is listed below: 

- [x] The students document in the README how compilation has been implemented and unit-tested.
- [x] The students document in the README how test execution has been implemented and unit-tested.
- [x] Document in the README how notification has been implemented and unit-tested.
- [x] Statement of contributions 
- [x] How to build and what the project is about

**Comment by gpihl** [comment]
Everything is checked now, closing.
